name: paper
description: The Paper is a implementation of Flx Design System for Flutter.
version: 0.1.0
homepage: https://github.com/the-flx/paper

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter